version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:5000'
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    depends_on:
      - db
    env_file:
      - .env-prod

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: python consumer.py
    depends_on:
      - db
    env_file:
      - .env-prod

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: vlad2
      POSTGRES_PASSWORD: qseawdzxc12
      POSTGRES_DB: main2
    ports:
      - "5433:5432"
    volumes:
      - .:/app