version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - .env-prod

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: python consumer.py
    depends_on:
     - db
    env_file:
      - .env-prod

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: qseawdzxc1
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - .:/app